### ISSUE TITLE
Any plans to update it？

### ISSUE THREAD

**Issue by fhefh2015** [xAlien95/shortcut-preview#2]
This project is great!
The workflow version is 3.0 now, any plans to update it?
There are many missing actions.

**Comment by xAlien95** [comment]
Thank you! Originally I was working on an Electron-based Shortcut editor which I never publicly released and this package was just a component of it. I abandoned that project when a rumor about the possibility of Apple working on a Catalyst port of the official Shortcuts app on macOS started to surface.
Since we still don't have a Shortcuts app I may get back on it and consequently update this side-package. At the moment I'm quite busy, but I'll update this GitHub issue when I'll be able to work on it.

In the meantime, feel free to fork this repo if you want to add features or actions not yet available.
